/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'massimobattestini' at '5/12/16 6:08 PM' with Gradle 2.8
 *
 * @author massimobattestini, @date 5/12/16 6:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
